Rename sketch folder to match sketch name
The Arduino IDE requires that a sketch be located in a folder of the same name. When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:

The file "jump_on_it.ino" needs to be inside a sketch folder named "jump_on_it".
Create this folder, move the file, and continue?

After clicking "OK" the Arduino IDE currently moves only the file jump_on_it.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:

C:\Users\per\Desktop\esp-jump-on-it-master\src\jump_on_it\jump_on_it.ino: In function 'void setup()':

jump_on_it:96: error: 'POLL_SECONDS' was not declared in this scope

     ESP.deepSleep(POLL_SECONDS * 1000000, WAKE_RF_DEFAULT);

                   ^

C:\Users\per\Desktop\esp-jump-on-it-master\src\jump_on_it\jump_on_it.ino: In function 'String download_prediction_json(int&, int&, int&, int&)':

jump_on_it:156: error: 'lat' was not declared in this scope

             lat, lon, access_key);

             ^

jump_on_it:156: error: 'lon' was not declared in this scope

             lat, lon, access_key);

                  ^

jump_on_it:156: error: 'access_key' was not declared in this scope

             lat, lon, access_key);

                       ^

jump_on_it:163: error: 'auth' was not declared in this scope

                      "Authorization: Basic " + String(auth) + "\r\n" +